---
sudo: required
language: python
services:
  - docker
before_install:
  - pip install ansible
install:
  - pip install molecule docker
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
